### ISSUE TITLE
Error: Cannot perform mod 0 exception on valid input

### ISSUE THREAD

**Issue by ktonon** [prozacchiwawa/elm-urlbase64#1]
https://ellie-app.com/4hnngnG866Va1

In short, `UrlBase64.decode (\_ -> Ok "Succeeded") "NDU2"` should produce a `Result` but instead an exception is thrown.

**Comment by prozacchiwawa** [comment]
Thanks, I'll fix that tonight.

**Comment by prozacchiwawa** [comment]
Published 1.0.2, should fix this.

Also, it wraps another base64 library (so giving \_ -> Ok "Succeeded" will
cause it to always return Ok "Succeeded").  This was to allow the user to
use a base64 library with whatever utf-8 handling or not they wanted.  I
kind of regret setting the result explicitly to String as otherwise, a
base64 decoder yielding Bytes would work without an update.  Will fix that
soon.

When ellie rescans package.elm-lang.org I'll make a fixed version of your
code and elm-urlbase64 working as intended.

**Comment by prozacchiwawa** [comment]
https://ellie-app.com/4hrtJy2k3Qra1

**Comment by ktonon** [comment]
Thank you for the quick turn around!
